import { MigrationInterface, QueryRunner } from "typeorm";

export class RefactorIncendios1780684348282 implements MigrationInterface {
    name = 'RefactorIncendios1780684348282'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "roles" ("rol_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" text NOT NULL, "descripcion" text, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_a5be7aa67e759e347b1c6464e10" UNIQUE ("nombre"), CONSTRAINT "PK_24cab7a48925a16ac7f4aee590c" PRIMARY KEY ("rol_uuid"))`);
        await queryRunner.query(`CREATE TABLE "instituciones" ("institucion_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" text NOT NULL, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_f54d2a3573c21c9effef8ae5712" UNIQUE ("nombre"), CONSTRAINT "PK_1f4740061443ac9950878ec985c" PRIMARY KEY ("institucion_uuid"))`);
        await queryRunner.query(`CREATE TABLE "usuarios" ("usuario_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" text, "apellido" text, "telefono" text, "email" text, "password_hash" text NOT NULL, "is_admin" boolean NOT NULL DEFAULT false, "es_miembro_institucion" boolean NOT NULL DEFAULT false, "ultimo_login" TIMESTAMP WITH TIME ZONE, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, "rol_uuid" uuid NOT NULL, "institucion_uuid" uuid, CONSTRAINT "PK_d5ba74a5cfa5fdc7233ba2e632a" PRIMARY KEY ("usuario_uuid"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_usuarios_email_notnull" ON "usuarios" ("email") WHERE "email" IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "estado_incendio" ("estado_incendio_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "codigo" text NOT NULL, "nombre" text NOT NULL, "orden" integer NOT NULL, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_b2656deef89f9ea62cce63e99ec" UNIQUE ("codigo"), CONSTRAINT "PK_b6aabb66588f03a19763ed0f170" PRIMARY KEY ("estado_incendio_uuid"))`);
        await queryRunner.query(`CREATE TABLE "incendio_localizaciones" ("incendio_uuid" uuid NOT NULL, "coordenada_x" double precision, "coordenada_y" double precision, "zona" text, "altitud" double precision, "departamento" text, "municipio" text, "region_inab" text, "subregion_inab" text, "lugar_poblado" text, "finca" text, CONSTRAINT "PK_35d6911a56382d7c85b5d1a139c" PRIMARY KEY ("incendio_uuid"))`);
        await queryRunner.query(`CREATE TABLE "incendio_controles" ("incendio_uuid" uuid NOT NULL, "es_forestal" boolean, "llegada_terrestres_at" TIMESTAMP WITH TIME ZONE, "llegada_aereos_at" TIMESTAMP WITH TIME ZONE, "controlado_at" TIMESTAMP WITH TIME ZONE, "extinguido_at" TIMESTAMP WITH TIME ZONE, "topografia_plano_pct" double precision, "topografia_ondulado_pct" double precision, "topografia_quebrado_pct" double precision, "tipo_propiedad" text, "iniciado_junto_a" text, "tipo_rastrero_pct" double precision, "tipo_copas_pct" double precision, "tipo_subterraneo_pct" double precision, "tecnica_directo_pct" double precision, "tecnica_indirecto_pct" double precision, "tecnica_natural_pct" double precision, "causa_incendio" text, "causa_otra" text, CONSTRAINT "PK_897cbef8740f973e0f7bcf444a5" PRIMARY KEY ("incendio_uuid"))`);
        await queryRunner.query(`CREATE TABLE "incendio_vegetaciones" ("incendio_uuid" uuid NOT NULL, "area_total_ha" double precision, "dentro_ap_ha" double precision, "fuera_ap_ha" double precision, "tipo_areas_quemadas" text, "bosque_conifera_dentro_ha" double precision, "bosque_conifera_fuera_ha" double precision, "bosque_latifoliado_dentro_ha" double precision, "bosque_latifoliado_fuera_ha" double precision, "bosque_mixto_dentro_ha" double precision, "bosque_mixto_fuera_ha" double precision, "bosque_manglar_dentro_ha" double precision, "bosque_manglar_fuera_ha" double precision, "plantacion_conifera_dentro_ha" double precision, "plantacion_conifera_fuera_ha" double precision, "plantacion_latifoliado_dentro_ha" double precision, "plantacion_latifoliado_fuera_ha" double precision, "plantacion_mixto_dentro_ha" double precision, "plantacion_mixto_fuera_ha" double precision, "pastizal_dentro_ha" double precision, "pastizal_fuera_ha" double precision, "humedal_dentro_ha" double precision, "humedal_fuera_ha" double precision, "pajonal_dentro_ha" double precision, "pajonal_fuera_ha" double precision, "sabana_dentro_ha" double precision, "sabana_fuera_ha" double precision, "guamil_dentro_ha" double precision, "guamil_fuera_ha" double precision, CONSTRAINT "PK_7d753aeaeff474a6da77f681d2d" PRIMARY KEY ("incendio_uuid"))`);
        await queryRunner.query(`CREATE TABLE "incendio_medios" ("incendio_uuid" uuid NOT NULL, "inst_inab" integer, "inst_conred" integer, "inst_conap" integer, "inst_mindef" integer, "inst_municipalidades" integer, "inst_comunitarios" integer, "inst_mingob" integer, "inst_cuerpos_socorro" integer, "inst_marn" integer, "inst_maga" integer, "inst_civ" integer, "inst_asociaciones" integer, "inst_ongs" integer, "inst_otras" text, "aereo_avion_sobrevuelo" integer, "aereo_avion_cisterna" integer, "aereo_helibalde" integer, "aereo_monitoreo" integer, "terrestre_pickups" integer, "terrestre_camiones" integer, "terrestre_ambulancia" integer, "terrestre_microbuses" integer, "terrestre_motobombas" integer, "terrestre_cisternas" integer, "terrestre_motocicletas" integer, "terrestre_rescate" integer, "acuatico_lanchas" integer, "acuatico_otro" integer, "abasto_raciones_frias" integer, "abasto_incaparina" integer, "abasto_agua" integer, "abasto_raciones_calientes" integer, CONSTRAINT "PK_52ee463b0ca97e80f17fe3a6913" PRIMARY KEY ("incendio_uuid"))`);
        await queryRunner.query(`CREATE TABLE "incendio_meteorologia" ("incendio_uuid" uuid NOT NULL, "temperatura" double precision, "humedad_relativa" double precision, "velocidad_viento" double precision, "direccion_viento" text, CONSTRAINT "PK_65f76b47c80837c7b912a985ea2" PRIMARY KEY ("incendio_uuid"))`);
        await queryRunner.query(`CREATE TABLE "incendio_responsables" ("incendio_uuid" uuid NOT NULL, "reportado_por" text, "institucion" text, "otra_institucion" text, "telefono" text, "fecha_hora_aviso" TIMESTAMP WITH TIME ZONE, "medio_aviso" text, "resp_nombre" text, "resp_dependencia" text, "resp_otra_dependencia" text, "resp_cargo" text, "resp_telefono" text, "resp_correo" text, "observaciones" text, CONSTRAINT "PK_cf60f60793e5807ec8df1c0f4ab" PRIMARY KEY ("incendio_uuid"))`);
        await queryRunner.query(`CREATE TABLE "incendio_seguidores" ("incendio_uuid" uuid NOT NULL, "usuario_uuid" uuid NOT NULL, "creado_en" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5491ee77fa5b5649ec8ede9fb2a" PRIMARY KEY ("incendio_uuid", "usuario_uuid"))`);
        await queryRunner.query(`CREATE TABLE "incendios" ("incendio_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "requiere_aprobacion" boolean NOT NULL DEFAULT true, "aprobado" boolean NOT NULL DEFAULT false, "aprobado_en" TIMESTAMP WITH TIME ZONE, "rechazado_en" TIMESTAMP WITH TIME ZONE, "motivo_rechazo" text, "titulo" text, "descripcion" text, "centroide" geometry(Point,4326), "inab_objectid" integer, "inab_globalid" text, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, "creado_por_uuid" uuid NOT NULL, "aprobado_por" uuid, "rechazado_por" uuid, "estado_incendio_uuid" uuid NOT NULL, CONSTRAINT "UQ_48dbb5aac3ef967291b5d17e9fa" UNIQUE ("inab_objectid"), CONSTRAINT "PK_6c7b9e2d55a7b6ae15449667281" PRIMARY KEY ("incendio_uuid"))`);
        await queryRunner.query(`CREATE INDEX "idx_incendios_estado_aprobado" ON "incendios" ("estado_incendio_uuid", "aprobado") `);
        await queryRunner.query(`CREATE TABLE "info_falsa_incendio" ("info_falsa_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "razon" text, "descripcion_detallada" text, "validador_nombre" character varying(150), "validador_contacto" character varying(50), "fecha_verificacion" TIMESTAMP WITH TIME ZONE, "ubicacion_verificada" geometry(Point,4326), "duplicado_de_incendio_uuid" uuid, "score_confianza" integer, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "incendio_uuid" uuid, "institucion_validadora_uuid" uuid, CONSTRAINT "PK_2439f14ecaed0b89fde40f9a50f" PRIMARY KEY ("info_falsa_uuid"))`);
        await queryRunner.query(`CREATE TABLE "incendio_registro_responsable" ("incendio_uuid" uuid NOT NULL, "nombre" text NOT NULL, "cargo" text, "telefono" text, "correo" text, "observaciones" text, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, "institucion_uuid" uuid, CONSTRAINT "PK_dcc100713eeb9bd4c5e7b181695" PRIMARY KEY ("incendio_uuid"))`);
        await queryRunner.query(`CREATE TABLE "notificaciones" ("notificacion_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "usuario_uuid" uuid NOT NULL, "titulo" character varying(255) NOT NULL, "mensaje" text NOT NULL, "tipo" character varying(50), "leida_en" TIMESTAMP WITH TIME ZONE, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "payload" jsonb, CONSTRAINT "PK_f4228a4d04139e6fb3f6685bae4" PRIMARY KEY ("notificacion_uuid"))`);
        await queryRunner.query(`CREATE TABLE "user_push_prefs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" character varying(64) NOT NULL, "municipios_suscritos" text array NOT NULL DEFAULT '{}', "departamentos_suscritos" text array NOT NULL DEFAULT '{}', "avisarme_aprobado" boolean NOT NULL DEFAULT true, "avisarme_actualizaciones" boolean NOT NULL DEFAULT true, "avisarme_cierres" boolean NOT NULL DEFAULT true, "extra" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_a9bd55654bdec0313c3c69fc2d4" UNIQUE ("user_id"), CONSTRAINT "PK_d12decaf0292237e98c9300912b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_user_push_prefs_user_id" ON "user_push_prefs" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "user_push_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token" character varying(255) NOT NULL, "user_id" character varying(64) NOT NULL, "prefs_id" uuid NOT NULL, "active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_d6456dfc0da765c6f7b5a2b6286" UNIQUE ("token"), CONSTRAINT "PK_8c8f0464a60f972981a76fe0ef5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_user_push_token_token" ON "user_push_tokens" ("token") `);
        await queryRunner.query(`CREATE INDEX "idx_user_push_token_user_id" ON "user_push_tokens" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "job_runs" ("job_run_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre_job" text NOT NULL, "inicio" TIMESTAMP WITH TIME ZONE NOT NULL, "fin" TIMESTAMP WITH TIME ZONE, "status" text NOT NULL, "insertados" integer NOT NULL DEFAULT '0', "ignorados" integer NOT NULL DEFAULT '0', "asociados" integer NOT NULL DEFAULT '0', "errores" jsonb, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1dc0ec4f3a3fb6f828ddbbe2dfa" PRIMARY KEY ("job_run_uuid"))`);
        await queryRunner.query(`CREATE INDEX "idx_job_runs" ON "job_runs" ("nombre_job", "inicio") `);
        await queryRunner.query(`CREATE TABLE "incendio_estado_historial" ("historial_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "observacion" text, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, "incendio_uuid" uuid NOT NULL, "estado_incendio_uuid" uuid NOT NULL, "cambiado_por" uuid, CONSTRAINT "PK_883562229677f4e9c4c96cf1376" PRIMARY KEY ("historial_uuid"))`);
        await queryRunner.query(`CREATE INDEX "idx_historial_incendio_fecha" ON "incendio_estado_historial" ("incendio_uuid", "creado_en") `);
        await queryRunner.query(`CREATE TABLE "fotos_reporte" ("foto_reporte_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "url" text NOT NULL, "credito" text, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, "incendio_uuid" uuid NOT NULL, CONSTRAINT "PK_288577555e842613a2f8831bd06" PRIMARY KEY ("foto_reporte_uuid"))`);
        await queryRunner.query(`CREATE INDEX "idx_fotos_reporte_incendio" ON "fotos_reporte" ("incendio_uuid") `);
        await queryRunner.query(`CREATE TABLE "zonas_afectadas" ("zona_afectada_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "geom" geometry(MultiPolygon,4326) NOT NULL, "fecha" date NOT NULL, "fuente" text, "metodo" text, "area_ha" numeric, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, "incendio_uuid" uuid NOT NULL, CONSTRAINT "PK_b34401004baad53d3a6c32e33f8" PRIMARY KEY ("zona_afectada_uuid"))`);
        await queryRunner.query(`CREATE INDEX "idx_zonas_afectadas_incendio_fecha" ON "zonas_afectadas" ("incendio_uuid", "fecha") `);
        await queryRunner.query(`CREATE TABLE "puntos_calor" ("punto_calor_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "fuente" text NOT NULL, "instrument" text NOT NULL, "satellite" text NOT NULL, "version" text, "acq_date" date NOT NULL, "acq_time" integer NOT NULL, "daynight" text, "confidence" numeric, "frp" numeric, "brightness" numeric, "bright_ti4" numeric, "bright_ti5" numeric, "scan" numeric, "track" numeric, "geom" geometry(Point,4326) NOT NULL, "region" text, "hash_dedupe" text, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, "incendio_uuid" uuid, CONSTRAINT "PK_e138bd05e2ad8cf6dcc5ce14b1f" PRIMARY KEY ("punto_calor_uuid"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_puntos_calor_hash_dedupe" ON "puntos_calor" ("hash_dedupe") `);
        await queryRunner.query(`CREATE INDEX "idx_puntos_calor_fecha" ON "puntos_calor" ("acq_date") `);
        await queryRunner.query(`CREATE TABLE "cierre_eventos_operativos" ("evento_operativo_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "tipo_evento" text NOT NULL, "categoria" text NOT NULL, "recurso_id" text, "ocurrio_en" TIMESTAMP WITH TIME ZONE NOT NULL, "nota" text, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, "incendio_uuid" uuid NOT NULL, "creado_por" uuid, CONSTRAINT "PK_a90621ae0868b96e5af4cb85997" PRIMARY KEY ("evento_operativo_uuid"))`);
        await queryRunner.query(`CREATE INDEX "idx_eventos_operativos_incendio_fecha" ON "cierre_eventos_operativos" ("incendio_uuid", "ocurrio_en") `);
        await queryRunner.query(`CREATE TABLE "actualizaciones" ("actualizacion_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "tipo" text NOT NULL, "descripcion_corta" text, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, "incendio_uuid" uuid NOT NULL, "creado_por" uuid, "historial_uuid" uuid, "foto_reporte_uuid" uuid, "responsable_incendio_uuid" uuid, "zona_afectada_uuid" uuid, "punto_calor_uuid" uuid, "evento_operativo_uuid" uuid, CONSTRAINT "PK_4cae633538702069815393c0816" PRIMARY KEY ("actualizacion_uuid"))`);
        await queryRunner.query(`CREATE INDEX "idx_actualizaciones_creado_en" ON "actualizaciones" ("creado_en") `);
        await queryRunner.query(`CREATE INDEX "idx_actualizaciones_incendio_fecha" ON "actualizaciones" ("incendio_uuid", "creado_en") `);
        await queryRunner.query(`CREATE TABLE "departamentos" ("departamento_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" text NOT NULL, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_324052d75576efdbc10ba3e8997" UNIQUE ("nombre"), CONSTRAINT "PK_73b30694d3e85fecea350dc8c95" PRIMARY KEY ("departamento_uuid"))`);
        await queryRunner.query(`CREATE TABLE "municipios" ("municipio_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" text NOT NULL, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, "departamento_uuid" uuid NOT NULL, CONSTRAINT "PK_c48a5aceeed09300c9e7a690340" PRIMARY KEY ("municipio_uuid"))`);
        await queryRunner.query(`CREATE INDEX "idx_municipios_depto_nombre" ON "municipios" ("departamento_uuid", "nombre") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_municipios_depto_nombre" ON "municipios" ("departamento_uuid", "nombre") `);
        await queryRunner.query(`CREATE TABLE "medios" ("medio_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" text NOT NULL, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_cdf1be33891d0fdef9990ff7649" UNIQUE ("nombre"), CONSTRAINT "PK_d95c98c8cfe783f2852f33d055a" PRIMARY KEY ("medio_uuid"))`);
        await queryRunner.query(`CREATE TABLE "auditoria_eventos" ("auditoria_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "tabla" text NOT NULL, "registro_id" text NOT NULL, "accion" text NOT NULL, "antes" jsonb, "despues" jsonb, "usuario_uuid" uuid, "ip" text, "user_agent" text, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_597e337f6469aeadbd65c347977" PRIMARY KEY ("auditoria_uuid"))`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "fk_usuarios_rol_uuid" FOREIGN KEY ("rol_uuid") REFERENCES "roles"("rol_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "fk_usuarios_institucion_uuid" FOREIGN KEY ("institucion_uuid") REFERENCES "instituciones"("institucion_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incendio_localizaciones" ADD CONSTRAINT "FK_35d6911a56382d7c85b5d1a139c" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incendio_controles" ADD CONSTRAINT "FK_897cbef8740f973e0f7bcf444a5" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incendio_vegetaciones" ADD CONSTRAINT "FK_7d753aeaeff474a6da77f681d2d" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incendio_medios" ADD CONSTRAINT "FK_52ee463b0ca97e80f17fe3a6913" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incendio_meteorologia" ADD CONSTRAINT "FK_65f76b47c80837c7b912a985ea2" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incendio_responsables" ADD CONSTRAINT "FK_cf60f60793e5807ec8df1c0f4ab" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incendio_seguidores" ADD CONSTRAINT "FK_eb6ecbbb178a7495c8031894230" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incendio_seguidores" ADD CONSTRAINT "FK_7785b1d74a901ee28915c6efbea" FOREIGN KEY ("usuario_uuid") REFERENCES "usuarios"("usuario_uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incendios" ADD CONSTRAINT "fk_incendios_creado_por_uuid" FOREIGN KEY ("creado_por_uuid") REFERENCES "usuarios"("usuario_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incendios" ADD CONSTRAINT "fk_incendios_aprobado_por" FOREIGN KEY ("aprobado_por") REFERENCES "usuarios"("usuario_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incendios" ADD CONSTRAINT "fk_incendios_rechazado_por" FOREIGN KEY ("rechazado_por") REFERENCES "usuarios"("usuario_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incendios" ADD CONSTRAINT "fk_incendios_estado" FOREIGN KEY ("estado_incendio_uuid") REFERENCES "estado_incendio"("estado_incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "info_falsa_incendio" ADD CONSTRAINT "FK_01108fb07a7c4c27ba498d6013c" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "info_falsa_incendio" ADD CONSTRAINT "FK_54ad201cb8f56da92bc618b2841" FOREIGN KEY ("institucion_validadora_uuid") REFERENCES "instituciones"("institucion_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incendio_registro_responsable" ADD CONSTRAINT "fk_resp_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incendio_registro_responsable" ADD CONSTRAINT "fk_resp_institucion_uuid" FOREIGN KEY ("institucion_uuid") REFERENCES "instituciones"("institucion_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_push_tokens" ADD CONSTRAINT "FK_391cd83ff35b55a121fe37fbe97" FOREIGN KEY ("prefs_id") REFERENCES "user_push_prefs"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "incendio_estado_historial" ADD CONSTRAINT "fk_historial_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incendio_estado_historial" ADD CONSTRAINT "fk_historial_estado_uuid" FOREIGN KEY ("estado_incendio_uuid") REFERENCES "estado_incendio"("estado_incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incendio_estado_historial" ADD CONSTRAINT "fk_historial_cambiado_por" FOREIGN KEY ("cambiado_por") REFERENCES "usuarios"("usuario_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fotos_reporte" ADD CONSTRAINT "fk_fotos_reporte_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "zonas_afectadas" ADD CONSTRAINT "fk_zonas_afectadas_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "puntos_calor" ADD CONSTRAINT "fk_puntos_calor_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_eventos_operativos" ADD CONSTRAINT "fk_eventos_operativos_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_eventos_operativos" ADD CONSTRAINT "fk_eventos_operativos_creado_por" FOREIGN KEY ("creado_por") REFERENCES "usuarios"("usuario_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" ADD CONSTRAINT "fk_actualizaciones_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" ADD CONSTRAINT "fk_actualizaciones_creado_por" FOREIGN KEY ("creado_por") REFERENCES "usuarios"("usuario_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" ADD CONSTRAINT "fk_actualizaciones_historial_uuid" FOREIGN KEY ("historial_uuid") REFERENCES "incendio_estado_historial"("historial_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" ADD CONSTRAINT "fk_actualizaciones_foto_reporte_uuid" FOREIGN KEY ("foto_reporte_uuid") REFERENCES "fotos_reporte"("foto_reporte_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" ADD CONSTRAINT "fk_actualizaciones_responsable_uuid" FOREIGN KEY ("responsable_incendio_uuid") REFERENCES "incendio_registro_responsable"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" ADD CONSTRAINT "fk_actualizaciones_zona_uuid" FOREIGN KEY ("zona_afectada_uuid") REFERENCES "zonas_afectadas"("zona_afectada_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" ADD CONSTRAINT "fk_actualizaciones_punto_calor_uuid" FOREIGN KEY ("punto_calor_uuid") REFERENCES "puntos_calor"("punto_calor_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" ADD CONSTRAINT "fk_actualizaciones_evento_operativo_uuid" FOREIGN KEY ("evento_operativo_uuid") REFERENCES "cierre_eventos_operativos"("evento_operativo_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "municipios" ADD CONSTRAINT "fk_municipios_departamento_uuid" FOREIGN KEY ("departamento_uuid") REFERENCES "departamentos"("departamento_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "municipios" DROP CONSTRAINT "fk_municipios_departamento_uuid"`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" DROP CONSTRAINT "fk_actualizaciones_evento_operativo_uuid"`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" DROP CONSTRAINT "fk_actualizaciones_punto_calor_uuid"`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" DROP CONSTRAINT "fk_actualizaciones_zona_uuid"`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" DROP CONSTRAINT "fk_actualizaciones_responsable_uuid"`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" DROP CONSTRAINT "fk_actualizaciones_foto_reporte_uuid"`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" DROP CONSTRAINT "fk_actualizaciones_historial_uuid"`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" DROP CONSTRAINT "fk_actualizaciones_creado_por"`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" DROP CONSTRAINT "fk_actualizaciones_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "cierre_eventos_operativos" DROP CONSTRAINT "fk_eventos_operativos_creado_por"`);
        await queryRunner.query(`ALTER TABLE "cierre_eventos_operativos" DROP CONSTRAINT "fk_eventos_operativos_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "puntos_calor" DROP CONSTRAINT "fk_puntos_calor_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "zonas_afectadas" DROP CONSTRAINT "fk_zonas_afectadas_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "fotos_reporte" DROP CONSTRAINT "fk_fotos_reporte_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "incendio_estado_historial" DROP CONSTRAINT "fk_historial_cambiado_por"`);
        await queryRunner.query(`ALTER TABLE "incendio_estado_historial" DROP CONSTRAINT "fk_historial_estado_uuid"`);
        await queryRunner.query(`ALTER TABLE "incendio_estado_historial" DROP CONSTRAINT "fk_historial_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "user_push_tokens" DROP CONSTRAINT "FK_391cd83ff35b55a121fe37fbe97"`);
        await queryRunner.query(`ALTER TABLE "incendio_registro_responsable" DROP CONSTRAINT "fk_resp_institucion_uuid"`);
        await queryRunner.query(`ALTER TABLE "incendio_registro_responsable" DROP CONSTRAINT "fk_resp_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "info_falsa_incendio" DROP CONSTRAINT "FK_54ad201cb8f56da92bc618b2841"`);
        await queryRunner.query(`ALTER TABLE "info_falsa_incendio" DROP CONSTRAINT "FK_01108fb07a7c4c27ba498d6013c"`);
        await queryRunner.query(`ALTER TABLE "incendios" DROP CONSTRAINT "fk_incendios_estado"`);
        await queryRunner.query(`ALTER TABLE "incendios" DROP CONSTRAINT "fk_incendios_rechazado_por"`);
        await queryRunner.query(`ALTER TABLE "incendios" DROP CONSTRAINT "fk_incendios_aprobado_por"`);
        await queryRunner.query(`ALTER TABLE "incendios" DROP CONSTRAINT "fk_incendios_creado_por_uuid"`);
        await queryRunner.query(`ALTER TABLE "incendio_seguidores" DROP CONSTRAINT "FK_7785b1d74a901ee28915c6efbea"`);
        await queryRunner.query(`ALTER TABLE "incendio_seguidores" DROP CONSTRAINT "FK_eb6ecbbb178a7495c8031894230"`);
        await queryRunner.query(`ALTER TABLE "incendio_responsables" DROP CONSTRAINT "FK_cf60f60793e5807ec8df1c0f4ab"`);
        await queryRunner.query(`ALTER TABLE "incendio_meteorologia" DROP CONSTRAINT "FK_65f76b47c80837c7b912a985ea2"`);
        await queryRunner.query(`ALTER TABLE "incendio_medios" DROP CONSTRAINT "FK_52ee463b0ca97e80f17fe3a6913"`);
        await queryRunner.query(`ALTER TABLE "incendio_vegetaciones" DROP CONSTRAINT "FK_7d753aeaeff474a6da77f681d2d"`);
        await queryRunner.query(`ALTER TABLE "incendio_controles" DROP CONSTRAINT "FK_897cbef8740f973e0f7bcf444a5"`);
        await queryRunner.query(`ALTER TABLE "incendio_localizaciones" DROP CONSTRAINT "FK_35d6911a56382d7c85b5d1a139c"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "fk_usuarios_institucion_uuid"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "fk_usuarios_rol_uuid"`);
        await queryRunner.query(`DROP TABLE "auditoria_eventos"`);
        await queryRunner.query(`DROP TABLE "medios"`);
        await queryRunner.query(`DROP INDEX "public"."uq_municipios_depto_nombre"`);
        await queryRunner.query(`DROP INDEX "public"."idx_municipios_depto_nombre"`);
        await queryRunner.query(`DROP TABLE "municipios"`);
        await queryRunner.query(`DROP TABLE "departamentos"`);
        await queryRunner.query(`DROP INDEX "public"."idx_actualizaciones_incendio_fecha"`);
        await queryRunner.query(`DROP INDEX "public"."idx_actualizaciones_creado_en"`);
        await queryRunner.query(`DROP TABLE "actualizaciones"`);
        await queryRunner.query(`DROP INDEX "public"."idx_eventos_operativos_incendio_fecha"`);
        await queryRunner.query(`DROP TABLE "cierre_eventos_operativos"`);
        await queryRunner.query(`DROP INDEX "public"."idx_puntos_calor_fecha"`);
        await queryRunner.query(`DROP INDEX "public"."idx_puntos_calor_hash_dedupe"`);
        await queryRunner.query(`DROP TABLE "puntos_calor"`);
        await queryRunner.query(`DROP INDEX "public"."idx_zonas_afectadas_incendio_fecha"`);
        await queryRunner.query(`DROP TABLE "zonas_afectadas"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fotos_reporte_incendio"`);
        await queryRunner.query(`DROP TABLE "fotos_reporte"`);
        await queryRunner.query(`DROP INDEX "public"."idx_historial_incendio_fecha"`);
        await queryRunner.query(`DROP TABLE "incendio_estado_historial"`);
        await queryRunner.query(`DROP INDEX "public"."idx_job_runs"`);
        await queryRunner.query(`DROP TABLE "job_runs"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_push_token_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_push_token_token"`);
        await queryRunner.query(`DROP TABLE "user_push_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_push_prefs_user_id"`);
        await queryRunner.query(`DROP TABLE "user_push_prefs"`);
        await queryRunner.query(`DROP TABLE "notificaciones"`);
        await queryRunner.query(`DROP TABLE "incendio_registro_responsable"`);
        await queryRunner.query(`DROP TABLE "info_falsa_incendio"`);
        await queryRunner.query(`DROP INDEX "public"."idx_incendios_estado_aprobado"`);
        await queryRunner.query(`DROP TABLE "incendios"`);
        await queryRunner.query(`DROP TABLE "incendio_seguidores"`);
        await queryRunner.query(`DROP TABLE "incendio_responsables"`);
        await queryRunner.query(`DROP TABLE "incendio_meteorologia"`);
        await queryRunner.query(`DROP TABLE "incendio_medios"`);
        await queryRunner.query(`DROP TABLE "incendio_vegetaciones"`);
        await queryRunner.query(`DROP TABLE "incendio_controles"`);
        await queryRunner.query(`DROP TABLE "incendio_localizaciones"`);
        await queryRunner.query(`DROP TABLE "estado_incendio"`);
        await queryRunner.query(`DROP INDEX "public"."uq_usuarios_email_notnull"`);
        await queryRunner.query(`DROP TABLE "usuarios"`);
        await queryRunner.query(`DROP TABLE "instituciones"`);
        await queryRunner.query(`DROP TABLE "roles"`);
    }

}
